name: Release Go Module

on:
  push:
    tags:
      - "v*.*.*" # Only run on semver tags, e.g. v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # pick your Go version

      - name: Verify module builds
        run: |
          go mod tidy
          go build ./...
          go test ./...

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
